// Code generated by protoc-gen-go.
// source: factorial.proto
// DO NOT EDIT!

/*
Package factorial is a generated protocol buffer package.

It is generated from these files:
	factorial.proto

It has these top-level messages:
	FactorialRequest
	FactorialResponse
*/
package factorial

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FactorialRequest struct {
	N uint64 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *FactorialRequest) Reset()                    { *m = FactorialRequest{} }
func (m *FactorialRequest) String() string            { return proto.CompactTextString(m) }
func (*FactorialRequest) ProtoMessage()               {}
func (*FactorialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FactorialResponse struct {
	Result uint64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *FactorialResponse) Reset()                    { *m = FactorialResponse{} }
func (m *FactorialResponse) String() string            { return proto.CompactTextString(m) }
func (*FactorialResponse) ProtoMessage()               {}
func (*FactorialResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*FactorialRequest)(nil), "FactorialRequest")
	proto.RegisterType((*FactorialResponse)(nil), "FactorialResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MathService service

type MathServiceClient interface {
	Factorial(ctx context.Context, in *FactorialRequest, opts ...grpc.CallOption) (*FactorialResponse, error)
}

type mathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMathServiceClient(cc *grpc.ClientConn) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Factorial(ctx context.Context, in *FactorialRequest, opts ...grpc.CallOption) (*FactorialResponse, error) {
	out := new(FactorialResponse)
	err := grpc.Invoke(ctx, "/MathService/Factorial", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MathService service

type MathServiceServer interface {
	Factorial(context.Context, *FactorialRequest) (*FactorialResponse, error)
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_Factorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Factorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Factorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Factorial(ctx, req.(*FactorialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Factorial",
			Handler:    _MathService_Factorial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factorial.proto",
}

func init() { proto.RegisterFile("factorial.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4b, 0x4c, 0x2e,
	0xc9, 0x2f, 0xca, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0x12, 0x70,
	0x83, 0x09, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x70, 0x31, 0xe6, 0x49, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0xe6, 0x29, 0x69, 0x73, 0x09, 0x22, 0xa9, 0x28, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x81, 0xaa, 0x83,
	0xf2, 0x8c, 0x9c, 0xb9, 0xb8, 0x7d, 0x13, 0x4b, 0x32, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53,
	0x85, 0x4c, 0xb8, 0x38, 0xe1, 0x7a, 0x85, 0x04, 0xf5, 0xd0, 0x6d, 0x92, 0x12, 0xd2, 0xc3, 0x30,
	0x5a, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x34, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x39,
	0xe0, 0xc6, 0xad, 0x00, 0x00, 0x00,
}
